export const t = {
  appTitle: "Compagnon de route",
  portfolio: "Portefeuille",
  about: "À propos",
  // Défaut 13 : locale d'affichage des dates centralisée ici, pas en dur dans les composants.
  dateLocale: "fr-FR",
  analysisInterrupted: "Analyse interrompue",
  heroTitle1: "Mesurez la robustesse",
  heroTitle2: "de vos évaluations",
  heroTitle3: "à l'ère de l'IA générative",
  heroSubtitle: "Basé sur le protocole d'audit développé dans \"Évaluer en formation à l'ère de l'IA générative\" (Rochane Kherbouche, 2026).",
  btnAuditTitle: "Audit détaillé",
  btnAuditDesc: "Analysez une consigne précise sur 4 dimensions critiques avec l'IA.",
  btnQuickTitle: "Diagnostic rapide",
  btnQuickDesc: "8 questions pour évaluer votre profil de vulnérabilité sans IA.",
  step1Title: "1. Saisie de la consigne",
  step1Placeholder: "Ex: 'Rédigez un rapport de 5 pages sur l'impact de la RSE...'",
  btnNextContext: "Suivant : définir le contexte",
  step2Title: "2. Contexte de passage",
  step2Subtitle: "Précisez les conditions réelles de l'examen pour affiner le diagnostic.",
  examplePrefix: "Exemple :",
  q1Title: "Composante orale ou synchrone ?",
  q1Desc: "L'apprenant·e doit-il/elle s'exprimer de vive voix ou en direct ?",
  q1Options: [
    { label: 'Oui obligatoire', ex: 'Soutenance devant jury, examen oral en classe.' },
    { label: 'Oui optionnelle', ex: 'Participation orale possible mais non notée.' },
    { label: 'Non, asynchrone', ex: 'Dépôt d\'un document PDF ou fichier à distance.' }
  ],
  q2Title: "Nature des données ?",
  q2Desc: "Le sujet est-il généraliste ou ancré dans un vécu unique ?",
  q2Options: [
    { label: 'Données locales / confidentielles', ex: 'Problématique interne à une PME précise, vécu personnel.' },
    { label: 'Partiellement spécifiques', ex: 'Étude d\'un secteur d\'activité mais sans entreprise précise.' },
    { label: 'Données génériques', ex: 'Sujet théorique (ex: "Le rôle de l\'IA en RH"), trouvable sur le web.' }
  ],
  q3Title: "Évaluation du processus ?",
  q3Desc: "Notez-vous uniquement le résultat final ou les étapes de création ?",
  q3Options: [
    { label: 'Processus documenté et évalué', ex: 'Journal de bord requis, étapes notées au fil de l\'eau.' },
    { label: 'Demandé mais non évalué', ex: 'Brouillons demandés mais seule la note finale compte.' },
    { label: 'Seul le produit final', ex: 'Seul le rapport final est rendu et noté.' }
  ],
  btnLaunchAudit: "Lancer l'audit de robustesse",
  loadingWait: "L'analyse IA peut prendre jusqu'à 15 secondes",
  reportTitle: "Rapport de robustesse",
  btnCopyJson: "Copier JSON",
  btnNewAudit: "Nouveau diagnostic",
  stressTestTitle: "Stress-test simulé",
  stressTestMin: "min",
  stressTestPilotage: "pilotage",
  dimensionsTitle: "Les 4 dimensions",
  preuvesLabel: "Extraits de la consigne qui fondent la note :",
  vigilancePoints: "Points de vigilance",
  recsTitle: "Recommandations",
  recsSorted: "Classées de la fiche la plus robuste à la moins robuste.",
  ficheDeplier: "Fiche complète",
  ficheFormat: "Format",
  ficheDuree: "Durée",
  fichePublics: "Publics",
  fichePrincipe: "Principe",
  ficheAdaptations: "Adaptations",
  ficheCharge: "Charge",
  ficheInconnue: "Cette fiche est absente du référentiel local, contenu indisponible.",
  portfolioEmpty: "Votre portefeuille est vide.",
  portfolioStart: "Analyser une première consigne",
  quickTestTime: "3 minutes chrono",
  quickTestIntro: "Répondez aux 8 questions suivantes. Plus votre score sur 12 est élevé, plus votre évaluation est vulnérable face à l'IA.",
  quickTestYes: "Oui (+2)",
  quickTestPartial: "Partiellement (+1)",
  quickTestNo: "Non (0)",
  quickTestScoreEst: "Score de Vulnérabilité (Estimé)",
  quickTestAnswered: "répondue(s)",
  quickTestConfidence: "Indice de confiance",
  quickTestBack: "Retour à l'accueil",
  aboutTitle: "À propos",
  aboutP1: "est un outil d'aide à la décision pédagogique conçu pour auditer la robustesse des évaluations face aux outils d'IA générative.",
  aboutPrivacyTitle: "Confidentialité des données",
  aboutPrivacyDesc1: "Pas de base de données : aucune donnée n'est stockée sur nos serveurs.",
  aboutPrivacyDesc2: "Stockage local : votre portefeuille est enregistré uniquement dans votre propre navigateur.",
  aboutPrivacyDesc3: "Anonymat : l'outil ne nécessite aucune création de compte.",
  aboutP2: "Développé par Rochane Kherbouche comme ressource complémentaire à l'ouvrage \"Évaluer en formation à l'ère de l'IA générative\" (2026).",
  aboutBtnClose: "Fermer",
  copied: "Copié dans le presse-papier.",
  statusCritique: "Vulnérabilité CRITIQUE",
  statusElevee: "Vulnérabilité ÉLEVÉE",
  statusModeree: "Vulnérabilité MODÉRÉE",
  statusRobuste: "ROBUSTE",
  adviceCritique: "Reprendre le protocole complet du chapitre. Consigne très exposée.",
  adviceElevee: "Une refonte substantielle est nécessaire.",
  adviceModeree: "Consultez les Fiches 1 à 4 pour des adaptations ciblées.",
  adviceRobuste: "Votre évaluation semble solide. Les Fiches 5 et 6 permettent d'affiner."
};

export const LOADING_MESSAGES = [
  "Analyse de la structure sémantique...",
  "Évaluation du potentiel de reproduction par l'IA...",
  "Calcul du degré de contextualisation requis...",
  "Identification des dimensions tacites et réflexives...",
  "Vérification des leviers de multimodalité...",
  "Consultation de la base de remédiation (Fiches 1-8)...",
  "Génération des recommandations stratégiques...",
  "Finalisation du diagnostic de robustesse...",
  "L'IA affine ses conseils pédagogiques...",
  "Encore quelques secondes, le rapport arrive."
];
